---
name: DateTime-Util-Calc
version: 0.10
author:
  - |-
    (c) Copyright 2004-2005 Daisuke Maki E<lt>daisuke@cpan.orgE<gt>.
    All rights reserved.
abstract: DateTime Calculation Utilities
license: perl
requires:
  DateTime: 0
  Math::BigFloat: 0
  Math::BigInt: >= 1.77
  Math::Trig: 0
recommends:
  Math::BigInt::GMP: 0
build_requires:
  Test::More: 0
provides:
  DateTime::Util::Calc:
    file: lib/DateTime/Util/Calc.pm
    version: 0.10
generated_by: Module::Build version 0.2611
