--- #YAML:1.0
name: DateTime-Util-Calc
version: 0.01
license: perl
distribution_type: module
requires:
  DateTime: 0
  Math::Round: 0
  Math::Trig: 0
  POSIX: 0
  Params::Validate: 0
recommends:
  Math::BigFloat: 0
  Math::BigInt: 0
  Math::BigInt::GMP: 0
  perl: 5.6.1
build_requires:
  Test::More: 0
conflicts: {}
provides:
  DateTime::Util::Calc:
    file: lib/DateTime/Util/Calc.pm
    version: 0.01
generated_by: Module::Build version 0.21
