---
name: DateTime-Util-Calc
version: !!perl/hash:Module::Build::Version
  original: 0.11
  version:
    - 0
    - 110
author:
  - |-
    (c) Copyright 2004-2005 Daisuke Maki E<lt>daisuke@cpan.orgE<gt>.
    All rights reserved.
abstract: DateTime Calculation Utilities
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0
  Math::BigFloat: 0
  Math::BigInt: '>= 1.77'
  Math::Trig: 0
build_requires:
  Test::More: 0
recommends:
  Math::BigInt::GMP: 0
provides:
  DateTime::Util::Calc:
    file: lib/DateTime/Util/Calc.pm
    version: 0.11
generated_by: Module::Build version 0.2803
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
