abstract: DateTime Calculation Utilities
author: Copyright (c) 2004-2007 Daisuke Maki <daisuke@endeworks.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: DateTime-Util-Calc
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Math::BigInt::FastCalc: 0
  Math::BigInt::GMP: 0
  Math::BigInt::Pari: 0
requires: 
  DateTime: 0
  Math::BigFloat: 0
  Math::BigInt: 0
  Math::Trig: 0
  perl: 5.6.1
version: 0.13
